/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFeaturesRouteImport } from './routes/_authenticated/features'
import { Route as GuardianTripIdRouteImport } from './routes/guardian.$tripId'
import { Route as AuthenticatedFeaturesIndexRouteImport } from './routes/_authenticated/features.index'
import { Route as AuthenticatedFeaturesBudgetRouteImport } from './routes/_authenticated/features.budget'
import { Route as AuthenticatedFeaturesItineraryRouteImport } from './routes/_authenticated/features.itinerary'
import { Route as AuthenticatedFeaturesRoutingRouteImport } from './routes/_authenticated/features.routing'
import { Route as AuthenticatedFeaturesSafetyRouteImport } from './routes/_authenticated/features.safety'
import { Route as AuthenticatedFeaturesUnchartedRouteImport } from './routes/_authenticated/features.uncharted'
import { Route as GuardianTrackTripIdRouteImport } from './routes/guardian.track.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeaturesRoute = AuthenticatedFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuardianTripIdRoute = GuardianTripIdRouteImport.update({
  id: '/guardian/$tripId',
  path: '/guardian/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeaturesIndexRoute =
  AuthenticatedFeaturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const AuthenticatedFeaturesBudgetRoute =
  AuthenticatedFeaturesBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const AuthenticatedFeaturesItineraryRoute =
  AuthenticatedFeaturesItineraryRouteImport.update({
    id: '/itinerary',
    path: '/itinerary',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const AuthenticatedFeaturesRoutingRoute =
  AuthenticatedFeaturesRoutingRouteImport.update({
    id: '/routing',
    path: '/routing',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const AuthenticatedFeaturesSafetyRoute =
  AuthenticatedFeaturesSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const AuthenticatedFeaturesUnchartedRoute =
  AuthenticatedFeaturesUnchartedRouteImport.update({
    id: '/uncharted',
    path: '/uncharted',
    getParentRoute: () => AuthenticatedFeaturesRoute,
  } as any)
const GuardianTrackTripIdRoute = GuardianTrackTripIdRouteImport.update({
  id: '/guardian/track/$tripId',
  path: '/guardian/track/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof AuthenticatedFeaturesRouteWithChildren
  '/guardian/$tripId': typeof GuardianTripIdRoute
  '/features/budget': typeof AuthenticatedFeaturesBudgetRoute
  '/features/itinerary': typeof AuthenticatedFeaturesItineraryRoute
  '/features/routing': typeof AuthenticatedFeaturesRoutingRoute
  '/features/safety': typeof AuthenticatedFeaturesSafetyRoute
  '/features/uncharted': typeof AuthenticatedFeaturesUnchartedRoute
  '/guardian/track/$tripId': typeof GuardianTrackTripIdRoute
  '/features/': typeof AuthenticatedFeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/guardian/$tripId': typeof GuardianTripIdRoute
  '/features/budget': typeof AuthenticatedFeaturesBudgetRoute
  '/features/itinerary': typeof AuthenticatedFeaturesItineraryRoute
  '/features/routing': typeof AuthenticatedFeaturesRoutingRoute
  '/features/safety': typeof AuthenticatedFeaturesSafetyRoute
  '/features/uncharted': typeof AuthenticatedFeaturesUnchartedRoute
  '/guardian/track/$tripId': typeof GuardianTrackTripIdRoute
  '/features': typeof AuthenticatedFeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRouteWithChildren
  '/guardian/$tripId': typeof GuardianTripIdRoute
  '/_authenticated/features/budget': typeof AuthenticatedFeaturesBudgetRoute
  '/_authenticated/features/itinerary': typeof AuthenticatedFeaturesItineraryRoute
  '/_authenticated/features/routing': typeof AuthenticatedFeaturesRoutingRoute
  '/_authenticated/features/safety': typeof AuthenticatedFeaturesSafetyRoute
  '/_authenticated/features/uncharted': typeof AuthenticatedFeaturesUnchartedRoute
  '/guardian/track/$tripId': typeof GuardianTrackTripIdRoute
  '/_authenticated/features/': typeof AuthenticatedFeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/guardian/$tripId'
    | '/features/budget'
    | '/features/itinerary'
    | '/features/routing'
    | '/features/safety'
    | '/features/uncharted'
    | '/guardian/track/$tripId'
    | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/guardian/$tripId'
    | '/features/budget'
    | '/features/itinerary'
    | '/features/routing'
    | '/features/safety'
    | '/features/uncharted'
    | '/guardian/track/$tripId'
    | '/features'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/_authenticated/features'
    | '/guardian/$tripId'
    | '/_authenticated/features/budget'
    | '/_authenticated/features/itinerary'
    | '/_authenticated/features/routing'
    | '/_authenticated/features/safety'
    | '/_authenticated/features/uncharted'
    | '/guardian/track/$tripId'
    | '/_authenticated/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  GuardianTripIdRoute: typeof GuardianTripIdRoute
  GuardianTrackTripIdRoute: typeof GuardianTrackTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guardian/$tripId': {
      id: '/guardian/$tripId'
      path: '/guardian/$tripId'
      fullPath: '/guardian/$tripId'
      preLoaderRoute: typeof GuardianTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/features/': {
      id: '/_authenticated/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof AuthenticatedFeaturesIndexRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/_authenticated/features/budget': {
      id: '/_authenticated/features/budget'
      path: '/budget'
      fullPath: '/features/budget'
      preLoaderRoute: typeof AuthenticatedFeaturesBudgetRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/_authenticated/features/itinerary': {
      id: '/_authenticated/features/itinerary'
      path: '/itinerary'
      fullPath: '/features/itinerary'
      preLoaderRoute: typeof AuthenticatedFeaturesItineraryRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/_authenticated/features/routing': {
      id: '/_authenticated/features/routing'
      path: '/routing'
      fullPath: '/features/routing'
      preLoaderRoute: typeof AuthenticatedFeaturesRoutingRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/_authenticated/features/safety': {
      id: '/_authenticated/features/safety'
      path: '/safety'
      fullPath: '/features/safety'
      preLoaderRoute: typeof AuthenticatedFeaturesSafetyRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/_authenticated/features/uncharted': {
      id: '/_authenticated/features/uncharted'
      path: '/uncharted'
      fullPath: '/features/uncharted'
      preLoaderRoute: typeof AuthenticatedFeaturesUnchartedRouteImport
      parentRoute: typeof AuthenticatedFeaturesRoute
    }
    '/guardian/track/$tripId': {
      id: '/guardian/track/$tripId'
      path: '/guardian/track/$tripId'
      fullPath: '/guardian/track/$tripId'
      preLoaderRoute: typeof GuardianTrackTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedFeaturesRouteChildren {
  AuthenticatedFeaturesBudgetRoute: typeof AuthenticatedFeaturesBudgetRoute
  AuthenticatedFeaturesItineraryRoute: typeof AuthenticatedFeaturesItineraryRoute
  AuthenticatedFeaturesRoutingRoute: typeof AuthenticatedFeaturesRoutingRoute
  AuthenticatedFeaturesSafetyRoute: typeof AuthenticatedFeaturesSafetyRoute
  AuthenticatedFeaturesUnchartedRoute: typeof AuthenticatedFeaturesUnchartedRoute
  AuthenticatedFeaturesIndexRoute: typeof AuthenticatedFeaturesIndexRoute
}

const AuthenticatedFeaturesRouteChildren: AuthenticatedFeaturesRouteChildren = {
  AuthenticatedFeaturesBudgetRoute: AuthenticatedFeaturesBudgetRoute,
  AuthenticatedFeaturesItineraryRoute: AuthenticatedFeaturesItineraryRoute,
  AuthenticatedFeaturesRoutingRoute: AuthenticatedFeaturesRoutingRoute,
  AuthenticatedFeaturesSafetyRoute: AuthenticatedFeaturesSafetyRoute,
  AuthenticatedFeaturesUnchartedRoute: AuthenticatedFeaturesUnchartedRoute,
  AuthenticatedFeaturesIndexRoute: AuthenticatedFeaturesIndexRoute,
}

const AuthenticatedFeaturesRouteWithChildren =
  AuthenticatedFeaturesRoute._addFileChildren(
    AuthenticatedFeaturesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  GuardianTripIdRoute: GuardianTripIdRoute,
  GuardianTrackTripIdRoute: GuardianTrackTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
